import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

import {ThemeProvider} from "@mui/material/styles";
import {theme} from "../utils/theme";
import {Roboto} from "next/font/google";

import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import ShareIcon from "@mui/icons-material/Share";
import {Hidden, Icon, Stack} from "@mui/material";
import StarBorderIcon from "@mui/icons-material/StarBorder";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import AutorenewIcon from "@mui/icons-material/Autorenew";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import SaveIcon from '@mui/icons-material/Save';
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{backgroundColor: "#000"}}>
        <ThemeProvider theme={theme}>
          <Hidden mdDown >
            
            <AppBar position="static" sx={{bgcolor: "#272727", px: 3}}>
              <Stack
                direction={"row"}
                alignItems={"center"}
                justifyContent={"space-between"}
              >
                <Stack
                  direction={"row"}
                  justifyItems={"flex-start"}
                  alignItems={"center"}
                >
                  {" "}
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <MenuIcon />
                  </IconButton>
                  <Typography
                    variant="body2"
                    component="p"
                    sx={{flexGrow: 1, mr: 2}}
                  >
                    Home {">"} Dashboards {">"} NETH
                  </Typography>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <StarBorderIcon />
                  </IconButton>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <ShareIcon />
                  </IconButton>
                </Stack>

                <Stack
                  direction={"row"}
                  alignContent={"center"}
                  alignItems={"center"}
                >
                  <Button color="inherit">Add</Button>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <SaveIcon />
                  </IconButton>
                  
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <ChevronLeftIcon />
                  </IconButton>
                  <Box>
                    <Typography>{new Date().toString()}</Typography>
                  </Box>{" "}
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <ChevronRightIcon />
                  </IconButton>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <AutorenewIcon />
                  </IconButton>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <KeyboardArrowDownIcon />
                  </IconButton>
                  <IconButton
                    size="large"
                    edge="start"
                    color="inherit"
                    aria-label="menu"
                    sx={{mr: 2}}
                  >
                    <KeyboardArrowUpIcon />
                  </IconButton>
                </Stack>
              </Stack>
            </AppBar>
          </Hidden>
          <Box sx={{px: {xs: '0px',md: "35px"}}}>{children}</Box>{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
